### ISSUE TITLE
Black Box

### ISSUE THREAD

**Issue by Shivaniac007** [Q-Division-2018-2019/Team-18#3]
<img width="368" alt="capture" src="https://user-images.githubusercontent.com/46882703/52488644-46b12e00-2be6-11e9-9e78-c3f7090f4934.PNG">

**Comment by boharavarun** [comment]
![capture](https://user-images.githubusercontent.com/46937115/52499149-c5b36000-2c00-11e9-93b4-e679ff94cbe2.JPG)

**Comment by Shivaniac007** [comment]
<img width="368" alt="capture" src="https://user-images.githubusercontent.com/46882703/52517896-7f91e700-2c68-11e9-9cb1-09a6c8804183.PNG">
